apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
    role: master
    tier: backend
  name: mongoreceiptsvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
    role: master
    tier: backend
