apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    role: master
    tier: backend
  name: mongo-master-receipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: mongo
        role: master
        tier: backend
    spec:
      containers:
      - image: mongo
        name: mongo-master
        ports:
        - containerPort: 27017